# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ctts/MapfRepo/RHCR

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ctts/MapfRepo/RHCR

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ctts/MapfRepo/RHCR/CMakeFiles /home/ctts/MapfRepo/RHCR//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ctts/MapfRepo/RHCR/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lifelong

# Build rule for target.
lifelong: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lifelong
.PHONY : lifelong

# fast build rule for target.
lifelong/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/build
.PHONY : lifelong/fast

src/BasicGraph.o: src/BasicGraph.cpp.o
.PHONY : src/BasicGraph.o

# target to build an object file
src/BasicGraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/BasicGraph.cpp.o
.PHONY : src/BasicGraph.cpp.o

src/BasicGraph.i: src/BasicGraph.cpp.i
.PHONY : src/BasicGraph.i

# target to preprocess a source file
src/BasicGraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/BasicGraph.cpp.i
.PHONY : src/BasicGraph.cpp.i

src/BasicGraph.s: src/BasicGraph.cpp.s
.PHONY : src/BasicGraph.s

# target to generate assembly for a file
src/BasicGraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/BasicGraph.cpp.s
.PHONY : src/BasicGraph.cpp.s

src/BasicSystem.o: src/BasicSystem.cpp.o
.PHONY : src/BasicSystem.o

# target to build an object file
src/BasicSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/BasicSystem.cpp.o
.PHONY : src/BasicSystem.cpp.o

src/BasicSystem.i: src/BasicSystem.cpp.i
.PHONY : src/BasicSystem.i

# target to preprocess a source file
src/BasicSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/BasicSystem.cpp.i
.PHONY : src/BasicSystem.cpp.i

src/BasicSystem.s: src/BasicSystem.cpp.s
.PHONY : src/BasicSystem.s

# target to generate assembly for a file
src/BasicSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/BasicSystem.cpp.s
.PHONY : src/BasicSystem.cpp.s

src/BeeGraph.o: src/BeeGraph.cpp.o
.PHONY : src/BeeGraph.o

# target to build an object file
src/BeeGraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/BeeGraph.cpp.o
.PHONY : src/BeeGraph.cpp.o

src/BeeGraph.i: src/BeeGraph.cpp.i
.PHONY : src/BeeGraph.i

# target to preprocess a source file
src/BeeGraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/BeeGraph.cpp.i
.PHONY : src/BeeGraph.cpp.i

src/BeeGraph.s: src/BeeGraph.cpp.s
.PHONY : src/BeeGraph.s

# target to generate assembly for a file
src/BeeGraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/BeeGraph.cpp.s
.PHONY : src/BeeGraph.cpp.s

src/BeeSystem.o: src/BeeSystem.cpp.o
.PHONY : src/BeeSystem.o

# target to build an object file
src/BeeSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/BeeSystem.cpp.o
.PHONY : src/BeeSystem.cpp.o

src/BeeSystem.i: src/BeeSystem.cpp.i
.PHONY : src/BeeSystem.i

# target to preprocess a source file
src/BeeSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/BeeSystem.cpp.i
.PHONY : src/BeeSystem.cpp.i

src/BeeSystem.s: src/BeeSystem.cpp.s
.PHONY : src/BeeSystem.s

# target to generate assembly for a file
src/BeeSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/BeeSystem.cpp.s
.PHONY : src/BeeSystem.cpp.s

src/ECBS.o: src/ECBS.cpp.o
.PHONY : src/ECBS.o

# target to build an object file
src/ECBS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/ECBS.cpp.o
.PHONY : src/ECBS.cpp.o

src/ECBS.i: src/ECBS.cpp.i
.PHONY : src/ECBS.i

# target to preprocess a source file
src/ECBS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/ECBS.cpp.i
.PHONY : src/ECBS.cpp.i

src/ECBS.s: src/ECBS.cpp.s
.PHONY : src/ECBS.s

# target to generate assembly for a file
src/ECBS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/ECBS.cpp.s
.PHONY : src/ECBS.cpp.s

src/ECBSNode.o: src/ECBSNode.cpp.o
.PHONY : src/ECBSNode.o

# target to build an object file
src/ECBSNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/ECBSNode.cpp.o
.PHONY : src/ECBSNode.cpp.o

src/ECBSNode.i: src/ECBSNode.cpp.i
.PHONY : src/ECBSNode.i

# target to preprocess a source file
src/ECBSNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/ECBSNode.cpp.i
.PHONY : src/ECBSNode.cpp.i

src/ECBSNode.s: src/ECBSNode.cpp.s
.PHONY : src/ECBSNode.s

# target to generate assembly for a file
src/ECBSNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/ECBSNode.cpp.s
.PHONY : src/ECBSNode.cpp.s

src/ID.o: src/ID.cpp.o
.PHONY : src/ID.o

# target to build an object file
src/ID.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/ID.cpp.o
.PHONY : src/ID.cpp.o

src/ID.i: src/ID.cpp.i
.PHONY : src/ID.i

# target to preprocess a source file
src/ID.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/ID.cpp.i
.PHONY : src/ID.cpp.i

src/ID.s: src/ID.cpp.s
.PHONY : src/ID.s

# target to generate assembly for a file
src/ID.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/ID.cpp.s
.PHONY : src/ID.cpp.s

src/KivaGraph.o: src/KivaGraph.cpp.o
.PHONY : src/KivaGraph.o

# target to build an object file
src/KivaGraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/KivaGraph.cpp.o
.PHONY : src/KivaGraph.cpp.o

src/KivaGraph.i: src/KivaGraph.cpp.i
.PHONY : src/KivaGraph.i

# target to preprocess a source file
src/KivaGraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/KivaGraph.cpp.i
.PHONY : src/KivaGraph.cpp.i

src/KivaGraph.s: src/KivaGraph.cpp.s
.PHONY : src/KivaGraph.s

# target to generate assembly for a file
src/KivaGraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/KivaGraph.cpp.s
.PHONY : src/KivaGraph.cpp.s

src/KivaSystem.o: src/KivaSystem.cpp.o
.PHONY : src/KivaSystem.o

# target to build an object file
src/KivaSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/KivaSystem.cpp.o
.PHONY : src/KivaSystem.cpp.o

src/KivaSystem.i: src/KivaSystem.cpp.i
.PHONY : src/KivaSystem.i

# target to preprocess a source file
src/KivaSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/KivaSystem.cpp.i
.PHONY : src/KivaSystem.cpp.i

src/KivaSystem.s: src/KivaSystem.cpp.s
.PHONY : src/KivaSystem.s

# target to generate assembly for a file
src/KivaSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/KivaSystem.cpp.s
.PHONY : src/KivaSystem.cpp.s

src/LRAStar.o: src/LRAStar.cpp.o
.PHONY : src/LRAStar.o

# target to build an object file
src/LRAStar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/LRAStar.cpp.o
.PHONY : src/LRAStar.cpp.o

src/LRAStar.i: src/LRAStar.cpp.i
.PHONY : src/LRAStar.i

# target to preprocess a source file
src/LRAStar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/LRAStar.cpp.i
.PHONY : src/LRAStar.cpp.i

src/LRAStar.s: src/LRAStar.cpp.s
.PHONY : src/LRAStar.s

# target to generate assembly for a file
src/LRAStar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/LRAStar.cpp.s
.PHONY : src/LRAStar.cpp.s

src/MAPFSolver.o: src/MAPFSolver.cpp.o
.PHONY : src/MAPFSolver.o

# target to build an object file
src/MAPFSolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/MAPFSolver.cpp.o
.PHONY : src/MAPFSolver.cpp.o

src/MAPFSolver.i: src/MAPFSolver.cpp.i
.PHONY : src/MAPFSolver.i

# target to preprocess a source file
src/MAPFSolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/MAPFSolver.cpp.i
.PHONY : src/MAPFSolver.cpp.i

src/MAPFSolver.s: src/MAPFSolver.cpp.s
.PHONY : src/MAPFSolver.s

# target to generate assembly for a file
src/MAPFSolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/MAPFSolver.cpp.s
.PHONY : src/MAPFSolver.cpp.s

src/OnlineGraph.o: src/OnlineGraph.cpp.o
.PHONY : src/OnlineGraph.o

# target to build an object file
src/OnlineGraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/OnlineGraph.cpp.o
.PHONY : src/OnlineGraph.cpp.o

src/OnlineGraph.i: src/OnlineGraph.cpp.i
.PHONY : src/OnlineGraph.i

# target to preprocess a source file
src/OnlineGraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/OnlineGraph.cpp.i
.PHONY : src/OnlineGraph.cpp.i

src/OnlineGraph.s: src/OnlineGraph.cpp.s
.PHONY : src/OnlineGraph.s

# target to generate assembly for a file
src/OnlineGraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/OnlineGraph.cpp.s
.PHONY : src/OnlineGraph.cpp.s

src/OnlineSystem.o: src/OnlineSystem.cpp.o
.PHONY : src/OnlineSystem.o

# target to build an object file
src/OnlineSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/OnlineSystem.cpp.o
.PHONY : src/OnlineSystem.cpp.o

src/OnlineSystem.i: src/OnlineSystem.cpp.i
.PHONY : src/OnlineSystem.i

# target to preprocess a source file
src/OnlineSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/OnlineSystem.cpp.i
.PHONY : src/OnlineSystem.cpp.i

src/OnlineSystem.s: src/OnlineSystem.cpp.s
.PHONY : src/OnlineSystem.s

# target to generate assembly for a file
src/OnlineSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/OnlineSystem.cpp.s
.PHONY : src/OnlineSystem.cpp.s

src/PBS.o: src/PBS.cpp.o
.PHONY : src/PBS.o

# target to build an object file
src/PBS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/PBS.cpp.o
.PHONY : src/PBS.cpp.o

src/PBS.i: src/PBS.cpp.i
.PHONY : src/PBS.i

# target to preprocess a source file
src/PBS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/PBS.cpp.i
.PHONY : src/PBS.cpp.i

src/PBS.s: src/PBS.cpp.s
.PHONY : src/PBS.s

# target to generate assembly for a file
src/PBS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/PBS.cpp.s
.PHONY : src/PBS.cpp.s

src/PBSNode.o: src/PBSNode.cpp.o
.PHONY : src/PBSNode.o

# target to build an object file
src/PBSNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/PBSNode.cpp.o
.PHONY : src/PBSNode.cpp.o

src/PBSNode.i: src/PBSNode.cpp.i
.PHONY : src/PBSNode.i

# target to preprocess a source file
src/PBSNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/PBSNode.cpp.i
.PHONY : src/PBSNode.cpp.i

src/PBSNode.s: src/PBSNode.cpp.s
.PHONY : src/PBSNode.s

# target to generate assembly for a file
src/PBSNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/PBSNode.cpp.s
.PHONY : src/PBSNode.cpp.s

src/PathTable.o: src/PathTable.cpp.o
.PHONY : src/PathTable.o

# target to build an object file
src/PathTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/PathTable.cpp.o
.PHONY : src/PathTable.cpp.o

src/PathTable.i: src/PathTable.cpp.i
.PHONY : src/PathTable.i

# target to preprocess a source file
src/PathTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/PathTable.cpp.i
.PHONY : src/PathTable.cpp.i

src/PathTable.s: src/PathTable.cpp.s
.PHONY : src/PathTable.s

# target to generate assembly for a file
src/PathTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/PathTable.cpp.s
.PHONY : src/PathTable.cpp.s

src/PriorityGraph.o: src/PriorityGraph.cpp.o
.PHONY : src/PriorityGraph.o

# target to build an object file
src/PriorityGraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/PriorityGraph.cpp.o
.PHONY : src/PriorityGraph.cpp.o

src/PriorityGraph.i: src/PriorityGraph.cpp.i
.PHONY : src/PriorityGraph.i

# target to preprocess a source file
src/PriorityGraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/PriorityGraph.cpp.i
.PHONY : src/PriorityGraph.cpp.i

src/PriorityGraph.s: src/PriorityGraph.cpp.s
.PHONY : src/PriorityGraph.s

# target to generate assembly for a file
src/PriorityGraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/PriorityGraph.cpp.s
.PHONY : src/PriorityGraph.cpp.s

src/ReservationTable.o: src/ReservationTable.cpp.o
.PHONY : src/ReservationTable.o

# target to build an object file
src/ReservationTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/ReservationTable.cpp.o
.PHONY : src/ReservationTable.cpp.o

src/ReservationTable.i: src/ReservationTable.cpp.i
.PHONY : src/ReservationTable.i

# target to preprocess a source file
src/ReservationTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/ReservationTable.cpp.i
.PHONY : src/ReservationTable.cpp.i

src/ReservationTable.s: src/ReservationTable.cpp.s
.PHONY : src/ReservationTable.s

# target to generate assembly for a file
src/ReservationTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/ReservationTable.cpp.s
.PHONY : src/ReservationTable.cpp.s

src/SIPP.o: src/SIPP.cpp.o
.PHONY : src/SIPP.o

# target to build an object file
src/SIPP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/SIPP.cpp.o
.PHONY : src/SIPP.cpp.o

src/SIPP.i: src/SIPP.cpp.i
.PHONY : src/SIPP.i

# target to preprocess a source file
src/SIPP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/SIPP.cpp.i
.PHONY : src/SIPP.cpp.i

src/SIPP.s: src/SIPP.cpp.s
.PHONY : src/SIPP.s

# target to generate assembly for a file
src/SIPP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/SIPP.cpp.s
.PHONY : src/SIPP.cpp.s

src/SingleAgentSolver.o: src/SingleAgentSolver.cpp.o
.PHONY : src/SingleAgentSolver.o

# target to build an object file
src/SingleAgentSolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/SingleAgentSolver.cpp.o
.PHONY : src/SingleAgentSolver.cpp.o

src/SingleAgentSolver.i: src/SingleAgentSolver.cpp.i
.PHONY : src/SingleAgentSolver.i

# target to preprocess a source file
src/SingleAgentSolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/SingleAgentSolver.cpp.i
.PHONY : src/SingleAgentSolver.cpp.i

src/SingleAgentSolver.s: src/SingleAgentSolver.cpp.s
.PHONY : src/SingleAgentSolver.s

# target to generate assembly for a file
src/SingleAgentSolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/SingleAgentSolver.cpp.s
.PHONY : src/SingleAgentSolver.cpp.s

src/SortingGraph.o: src/SortingGraph.cpp.o
.PHONY : src/SortingGraph.o

# target to build an object file
src/SortingGraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/SortingGraph.cpp.o
.PHONY : src/SortingGraph.cpp.o

src/SortingGraph.i: src/SortingGraph.cpp.i
.PHONY : src/SortingGraph.i

# target to preprocess a source file
src/SortingGraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/SortingGraph.cpp.i
.PHONY : src/SortingGraph.cpp.i

src/SortingGraph.s: src/SortingGraph.cpp.s
.PHONY : src/SortingGraph.s

# target to generate assembly for a file
src/SortingGraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/SortingGraph.cpp.s
.PHONY : src/SortingGraph.cpp.s

src/SortingSystem.o: src/SortingSystem.cpp.o
.PHONY : src/SortingSystem.o

# target to build an object file
src/SortingSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/SortingSystem.cpp.o
.PHONY : src/SortingSystem.cpp.o

src/SortingSystem.i: src/SortingSystem.cpp.i
.PHONY : src/SortingSystem.i

# target to preprocess a source file
src/SortingSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/SortingSystem.cpp.i
.PHONY : src/SortingSystem.cpp.i

src/SortingSystem.s: src/SortingSystem.cpp.s
.PHONY : src/SortingSystem.s

# target to generate assembly for a file
src/SortingSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/SortingSystem.cpp.s
.PHONY : src/SortingSystem.cpp.s

src/StateTimeAStar.o: src/StateTimeAStar.cpp.o
.PHONY : src/StateTimeAStar.o

# target to build an object file
src/StateTimeAStar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/StateTimeAStar.cpp.o
.PHONY : src/StateTimeAStar.cpp.o

src/StateTimeAStar.i: src/StateTimeAStar.cpp.i
.PHONY : src/StateTimeAStar.i

# target to preprocess a source file
src/StateTimeAStar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/StateTimeAStar.cpp.i
.PHONY : src/StateTimeAStar.cpp.i

src/StateTimeAStar.s: src/StateTimeAStar.cpp.s
.PHONY : src/StateTimeAStar.s

# target to generate assembly for a file
src/StateTimeAStar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/StateTimeAStar.cpp.s
.PHONY : src/StateTimeAStar.cpp.s

src/States.o: src/States.cpp.o
.PHONY : src/States.o

# target to build an object file
src/States.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/States.cpp.o
.PHONY : src/States.cpp.o

src/States.i: src/States.cpp.i
.PHONY : src/States.i

# target to preprocess a source file
src/States.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/States.cpp.i
.PHONY : src/States.cpp.i

src/States.s: src/States.cpp.s
.PHONY : src/States.s

# target to generate assembly for a file
src/States.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/States.cpp.s
.PHONY : src/States.cpp.s

src/WHCAStar.o: src/WHCAStar.cpp.o
.PHONY : src/WHCAStar.o

# target to build an object file
src/WHCAStar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/WHCAStar.cpp.o
.PHONY : src/WHCAStar.cpp.o

src/WHCAStar.i: src/WHCAStar.cpp.i
.PHONY : src/WHCAStar.i

# target to preprocess a source file
src/WHCAStar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/WHCAStar.cpp.i
.PHONY : src/WHCAStar.cpp.i

src/WHCAStar.s: src/WHCAStar.cpp.s
.PHONY : src/WHCAStar.s

# target to generate assembly for a file
src/WHCAStar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/WHCAStar.cpp.s
.PHONY : src/WHCAStar.cpp.s

src/common.o: src/common.cpp.o
.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i
.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s
.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/driver.o: src/driver.cpp.o
.PHONY : src/driver.o

# target to build an object file
src/driver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/driver.cpp.o
.PHONY : src/driver.cpp.o

src/driver.i: src/driver.cpp.i
.PHONY : src/driver.i

# target to preprocess a source file
src/driver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/driver.cpp.i
.PHONY : src/driver.cpp.i

src/driver.s: src/driver.cpp.s
.PHONY : src/driver.s

# target to generate assembly for a file
src/driver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lifelong.dir/build.make CMakeFiles/lifelong.dir/src/driver.cpp.s
.PHONY : src/driver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lifelong"
	@echo "... src/BasicGraph.o"
	@echo "... src/BasicGraph.i"
	@echo "... src/BasicGraph.s"
	@echo "... src/BasicSystem.o"
	@echo "... src/BasicSystem.i"
	@echo "... src/BasicSystem.s"
	@echo "... src/BeeGraph.o"
	@echo "... src/BeeGraph.i"
	@echo "... src/BeeGraph.s"
	@echo "... src/BeeSystem.o"
	@echo "... src/BeeSystem.i"
	@echo "... src/BeeSystem.s"
	@echo "... src/ECBS.o"
	@echo "... src/ECBS.i"
	@echo "... src/ECBS.s"
	@echo "... src/ECBSNode.o"
	@echo "... src/ECBSNode.i"
	@echo "... src/ECBSNode.s"
	@echo "... src/ID.o"
	@echo "... src/ID.i"
	@echo "... src/ID.s"
	@echo "... src/KivaGraph.o"
	@echo "... src/KivaGraph.i"
	@echo "... src/KivaGraph.s"
	@echo "... src/KivaSystem.o"
	@echo "... src/KivaSystem.i"
	@echo "... src/KivaSystem.s"
	@echo "... src/LRAStar.o"
	@echo "... src/LRAStar.i"
	@echo "... src/LRAStar.s"
	@echo "... src/MAPFSolver.o"
	@echo "... src/MAPFSolver.i"
	@echo "... src/MAPFSolver.s"
	@echo "... src/OnlineGraph.o"
	@echo "... src/OnlineGraph.i"
	@echo "... src/OnlineGraph.s"
	@echo "... src/OnlineSystem.o"
	@echo "... src/OnlineSystem.i"
	@echo "... src/OnlineSystem.s"
	@echo "... src/PBS.o"
	@echo "... src/PBS.i"
	@echo "... src/PBS.s"
	@echo "... src/PBSNode.o"
	@echo "... src/PBSNode.i"
	@echo "... src/PBSNode.s"
	@echo "... src/PathTable.o"
	@echo "... src/PathTable.i"
	@echo "... src/PathTable.s"
	@echo "... src/PriorityGraph.o"
	@echo "... src/PriorityGraph.i"
	@echo "... src/PriorityGraph.s"
	@echo "... src/ReservationTable.o"
	@echo "... src/ReservationTable.i"
	@echo "... src/ReservationTable.s"
	@echo "... src/SIPP.o"
	@echo "... src/SIPP.i"
	@echo "... src/SIPP.s"
	@echo "... src/SingleAgentSolver.o"
	@echo "... src/SingleAgentSolver.i"
	@echo "... src/SingleAgentSolver.s"
	@echo "... src/SortingGraph.o"
	@echo "... src/SortingGraph.i"
	@echo "... src/SortingGraph.s"
	@echo "... src/SortingSystem.o"
	@echo "... src/SortingSystem.i"
	@echo "... src/SortingSystem.s"
	@echo "... src/StateTimeAStar.o"
	@echo "... src/StateTimeAStar.i"
	@echo "... src/StateTimeAStar.s"
	@echo "... src/States.o"
	@echo "... src/States.i"
	@echo "... src/States.s"
	@echo "... src/WHCAStar.o"
	@echo "... src/WHCAStar.i"
	@echo "... src/WHCAStar.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/driver.o"
	@echo "... src/driver.i"
	@echo "... src/driver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

